export const mockProfiles = [
  {
    id: 'p1',
    name: 'Aarav Sharma',
    gender: 'Male',
    age: 29,
    height: 178,
    profession: 'Software Engineer',
    education: 'B.Tech, IIT Bombay',
    city: 'Bengaluru',
    location: 'Bengaluru, Karnataka',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/men/11.jpg',
    contact: '+91-98XXXXXX12',
    bio: 'Tech enthusiast with deep respect for tradition. Loves classical music and yoga.'
  },
  {
    id: 'p2',
    name: 'Ishita Joshi',
    gender: 'Female',
    age: 26,
    height: 165,
    profession: 'Doctor',
    education: 'MBBS, AFMC',
    city: 'Pune',
    location: 'Pune, Maharashtra',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/women/21.jpg',
    contact: '+91-97XXXXXX34',
    bio: 'Compassionate doctor who enjoys reading and volunteering. Family values are important to me.'
  },
  {
    id: 'p3',
    name: 'Rohan Iyer',
    gender: 'Male',
    age: 31,
    height: 175,
    profession: 'Investment Banker',
    education: 'MBA, IIM Ahmedabad',
    city: 'Mumbai',
    location: 'Mumbai, Maharashtra',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/men/32.jpg',
    contact: '+91-99XXXXXX88',
    bio: 'Ambitious yet grounded. Loves travel, fitness, and cherishes Indian heritage.'
  },
  {
    id: 'p4',
    name: 'Sanskriti Trivedi',
    gender: 'Female',
    age: 25,
    height: 162,
    profession: 'UX Designer',
    education: 'B.Des, NID',
    city: 'Ahmedabad',
    location: 'Ahmedabad, Gujarat',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/women/45.jpg',
    contact: '+91-96XXXXXX55',
    bio: 'Design thinker who appreciates art and culture. Weekend classical dance practitioner.'
  },
  {
    id: 'p5',
    name: 'Neeraj Kulkarni',
    gender: 'Male',
    age: 27,
    height: 173,
    profession: 'Data Scientist',
    education: 'M.S., Carnegie Mellon',
    city: 'Hyderabad',
    location: 'Hyderabad, Telangana',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/men/52.jpg',
    contact: '+91-95XXXXXX77',
    bio: 'Curious mind with love for statistics and Vedic literature.'
  },
  {
    id: 'p6',
    name: 'Nandita Deshpande',
    gender: 'Female',
    age: 28,
    height: 168,
    profession: 'Chartered Accountant',
    education: 'CA, ICAI',
    city: 'Pune',
    location: 'Pune, Maharashtra',
    caste: 'Brahmin',
    religion: 'Hindu',
    photo: 'https://randomuser.me/api/portraits/women/63.jpg',
    contact: '+91-94XXXXXX66',
    bio: 'Numbers by day, music by night. Family-oriented and spiritual.'
  },
]

export const memberships = [
  { id: 'free', name: 'Free', price: 0, features: ['Basic access', 'Limited profile views'] },
  { id: 'silver', name: 'Silver', price: 999, features: ['View more details', 'Priority support'] },
  { id: 'gold', name: 'Gold', price: 1999, features: ['Full access', 'See contact details', 'Smart match priority'] },
]
